document.addEventListener('DOMContentLoaded',()=>{
 const btn=document.querySelector('.menu-button'), panel=document.querySelector('.menu-panel');
 if(btn&&panel){const close=()=>{panel.classList.remove('open');btn.setAttribute('aria-expanded','false')};btn.addEventListener('click',e=>{e.stopPropagation();const o=panel.classList.toggle('open');btn.setAttribute('aria-expanded',String(o))});document.addEventListener('click',e=>{if(!panel.contains(e.target))close()});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});}
 const current=(location.pathname.split('/').pop()||'index.html').toLowerCase();document.querySelectorAll('.menu-panel a').forEach(a=>{if((a.getAttribute('href')||'').toLowerCase()===current)a.setAttribute('aria-current','page')});
 const rows=[...document.querySelectorAll('[data-room]')], estimate=document.getElementById('estimate'), detail=document.getElementById('estimateDetail');
 function calc(){if(!estimate)return;let total=0,lines=[];rows.forEach(r=>{const qty=Number(r.querySelector('input[type=number]')?.value||0),deep=r.querySelector('input[type=checkbox]')?.checked;const price=Number(deep?r.dataset.deep:r.dataset.standard);if(qty>0){total+=qty*price;lines.push(`${qty} × ${r.dataset.room}${deep?' (deep)':''}`)}});document.querySelectorAll('[data-addon-price]').forEach(a=>{if(a.checked){const price=Number(a.dataset.addonPrice||0);total+=price;lines.push(`${a.name} (+$${price})`)}});const minimum=total>0?Math.max(90,total):0;estimate.textContent=`$${minimum.toFixed(0)}`;detail.textContent=lines.length?lines.join(' • '):'Add rooms to build your estimate.';}
 rows.forEach(r=>r.querySelectorAll('input').forEach(i=>i.addEventListener('input',calc)));calc();
 const form=document.getElementById('quoteForm');if(form){form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const data=new FormData(form),lines=[];for(const [k,v] of data.entries())if(String(v).trim())lines.push(`${k}: ${v}`);if(estimate)lines.unshift(`Estimated room-based price: ${estimate.textContent}`);location.href=`mailto:randyspremiercleaning@gmail.com?subject=${encodeURIComponent('Free Quote Request - Randy Premier Cleaning')}&body=${encodeURIComponent(lines.join('\n'))}`})}
});

(()=>{const h=document.querySelector('.home-header');if(!h)return;const sync=()=>h.classList.toggle('scrolled',window.scrollY>32);sync();addEventListener('scroll',sync,{passive:true});})();
